- .github/workflows/storybook-deploy.yml
스토리북 깃허브페이지 자동배포 적용. dev 브랜치로 올라갈때 && component 디렉토리에 변경사항 있을때 액션으로 말아집니다.
feature/storybook
> feat: 스토리북 깃허브페이지 자동배포

- .github/workflows/docker-deploy.yml
feat: docker ci/cd 2트
feature/docker
몇트만에 성공할까요
> feat: docker ci/cd 2트

- .github/workflows/docker-deploy.yml
- Dockerfile.prod
- config/scripts/nginx/default.conf
feat: docker ci/cd 5트
feature/docker
몇트만에 성공할까요
> feat: docker ci/cd 5트

- config/nginx/default.conf
feat: docker ci/cd 6트
feature/docker
몇트만에 성공할까요
> feat: docker ci/cd 6트

- .github/workflows/prod-deploy.yml
- config/nginx/Dockerfile
- config/nginx/default.conf
> feat: docker ci/cd 8트

- .gitignore
- config/nginx/default.conf
> feat: docker ci/cd 9트

- package.json
> feat: docker ci/cd 9.1트

- .github/workflows/prod-deploy.yml
테스트완료~~~
feature/docker
*resolved: #19
> feat: docker ci/cd 10트

- package.json
- src/components/badges/InstructionBadge.stories.tsx
- src/components/badges/InstructionBadge.tsx
- src/components/badges/InterestBadge.stories.tsx
- src/components/badges/InterestBadge.tsx
- src/components/badges/RiskBadge.stories.tsx
- src/components/badges/RiskBadge.tsx
- src/components/badges/SuggestBadge.stories.tsx
- src/components/badges/SuggestBadge.tsx
- src/components/onboarding/ProfileButton.stories.tsx
- src/components/onboarding/ProfileButton.tsx
- src/lib/styles/styled.d.ts
- src/lib/styles/theme.tsx
- src/pages/TestPage.tsx
- yarn.lock
* 4가지 뱃지 컴포넌트 개발, 스토리 제작
* 폰트 미적용
feature/component-badges
* resolves #26
> [Feature/component-badges] 뱃지 컴포넌트 개발, 스토리 제작

- .github/workflows/storybook-deploy.yml
- src/components/common/badges/InstructionBadge.tsx
- src/store/slices/challengePayloadSlice.tsx
> fix : deploy

- src/components/common/button/InputForm.stories.tsx
- src/components/common/button/InputForm.tsx
refactor/input-button-components
> feat : 온보딩 페이지 생년월일 입력용 컴포넌트

- .github/workflows/prod-deploy.yml
> feat : dockerfile 테스트 수정

- Dockerfile.prod
> feat : dockerfile 테스트 수정 4트

- Dockerfile.prod
> feat : dockerfile 테스트 수정 5트

- Dockerfile.prod
- src/components/common/bottomSheet/sheetContent/RangeInput.tsx
- src/components/common/bottomSheet/sheetContent/SelectInterest.tsx
- src/components/common/button/InputForm.tsx
- src/components/kid/create/content/Step4.tsx
- src/components/kid/home/Summary.tsx
- src/lib/styles/styled.d.ts
- src/lib/utils/getChallengeStep4Prices.tsx
- src/lib/utils/getChallengeStep4Weeks.tsx
- src/store/slices/authSlice.tsx
자녀 홈 summary component, 돈길 계약하기 로직 진짜최종
refactor/component-layout
> 자녀 홈 summary component, 돈길 계약하기 로직 진짜최종

- Dockerfile.prod
> fix: docker build test2

- Dockerfile.prod
> fix: docker build test3

- src/store/slices/authSlice.tsx
> fix : auth slice inital

- src/pages/Home/Reject.tsx
> fix : 개멍청한 바텀시트 type 수정

- src/App.tsx
> fix: requireAuth 수정

- .github/workflows/prod-deploy.yml
> chore : github action env 파일

- src/components/common/modals/quaternaryModal/QuaternaryModal.tsx
- src/components/home/create/steps/Step5.tsx
- src/pages/OnBoarding/LoginPage.tsx
> chore : env test2

- .github/workflows/prod-deploy.yml
> chore : env test3

- src/components/common/modals/QuinaryModal.tsx
- src/components/common/modals/SenaryModal.tsx
- src/components/common/modals/quaternaryModal/QuaternaryModal.tsx
> chore : env test4

- src/App.tsx
- src/components/home/create/SelectItemNameButton.tsx
- src/components/home/walking/TotalInterest.tsx
- src/components/home/walking/WalkingDongilItem.tsx
- src/components/layout/Layout.tsx
- src/components/walk/WalkingItemNameButton.tsx
- src/index.tsx
- src/lib/styles/global-style.tsx
- src/pages/Home/Detail.tsx
- src/pages/OnBoarding/LoginPage.tsx
> 크로스브라우징 관련 이슈 해결

- src/components/common/buttons/RoleButton.tsx
- src/components/layout/Layout.tsx
- src/components/walk/SwipeToWalk.stories.tsx
- src/components/walk/WalkDefault.tsx
- src/components/walk/WalkingItemNameButton.stories.tsx
> QA : 안드로이드 기기 대응 

- src/components/home/create/Progress.tsx
- src/components/home/create/steps/Step5.tsx
돈길 생성후 받는 응답과 대기중인 돈길 정보 사이에 다른 값들이 많아서 스토어에 새로운 돈길을 추가하지 않고, 대기중인 돈길을 새로 패치합니다
fix/createDongil
> feat : 돈길 계약하기 후 대기중인 돈길 새로 패치, progress fill 오류 수정

- src/components/auth/RequireAuth.tsx
- src/components/home/ParentHome.tsx
- src/components/home/pending/PendingDongilSection.tsx
- src/components/home/proposed/ProposedDongilItem.tsx
- src/components/home/proposed/ProposedDongilList.tsx
- src/components/home/proposed/ProposedDongilSection.tsx
- src/components/home/thisWeekS/ThisWeekSDongilSection.tsx
- src/components/home/walking/WalkingDongilSection.tsx
- src/lib/api/axios.tsx
- src/lib/constants/index.tsx
- src/pages/OnBoarding/LoginPage.tsx
- src/pages/OnBoarding/OAuthRedirectPage.tsx
- src/store/slices/authSlice.tsx
- src/store/slices/familySlice.tsx
- src/store/slices/kidsSlice.tsx
- src/store/slices/pendingDongilsSlice.tsx
- src/store/slices/proposedDongilsSlice.tsx
- src/store/slices/thisWeekSDongilsSlice.tsx
- src/store/slices/walkingDongilsSlice.tsx
> main 병합 후 로그인 테스트를 위한 PR

- src/App.tsx
- src/components/common/modals/receiptModal/contents/BottomContent.tsx
> feat : s3 버킷 주소 main으로

- src/pages/Home/Alert.tsx
- src/store/slices/authSlice.tsx
> feat : 알림 없을때 뷰

- src/lib/constants/BASE_URL.ts
- src/lib/constants/KAKAO_AUTH_URL.ts
> feat : baseurl

- src/pages/Test/AuthTest.tsx
> grouplink postmesssage json -> string

- src/store/slices/authSlice.tsx
> feat : authSlice 초기화

- src/components/mypage/GroupLink.tsx
> fix : 가족 없을때 400에러 처리 - 그룹링크

- src/components/mypage/FamilyList.tsx
- src/components/mypage/GroupLink.tsx
- src/components/walk/SwipeToWalk.tsx
- src/pages/Mypage/Mypage.tsx
> fix : mutate convention

- src/components/common/bottomSheets/commonSheet/Completed.tsx
- src/components/home/detail/Detail.tsx
- src/components/home/pending/PendingDongilItem.tsx
- src/components/home/proposed/ProposedDongilItem.tsx
- src/components/home/walking/WalkingDongilItem.tsx
- src/components/home/walking/WalkingDongilSection.tsx
- src/components/manage/withdraw/WithdrawReason.tsx
- src/components/mypage/FamilyList.tsx
- src/components/mypage/useOpenGroupLinkSheets.ts
- src/components/register/RegisterRole.tsx
- src/components/walk/WalkError.tsx
- src/lib/hooks/useGlobalBottomSheet.tsx
- src/pages/Home/Reject.tsx
- src/pages/Manage/Manage.tsx
- src/pages/Manage/Withdraw/WithdrawCallbackPage.tsx
- src/pages/Mypage/Mypage.tsx
> refactor : 바텀시트 관련

- src/components/interest/interestHistory/WalkingDongilList.tsx
- src/components/layout/RouteTransition.tsx
- src/components/layout/transition.css
- src/pages/Home/Reject.tsx
- src/pages/Home/index.tsx
> fix : 메인라우팅 트랜지션 제거, interset- home 디테일페이지 뒤로가기 라우팅 수정

- src/components/layout/AppBar.tsx
- src/pages/Home/index.tsx
- src/pages/Interest/index.tsx
> fix : interestpage background

- src/components/home/detail/Detail.tsx
> fix : 포기하기 이후 렌더링 안되는 오류

- src/components/home/create/steps/Step1.tsx
- src/store/slices/createChallengeSlice.tsx
> refactor : createChallengeSlice

- src/components/home/detail/Detail.tsx
- src/components/home/detail/useTargetDongil.tsx
> fix: 돈길 상세 보기 진입 시 불필요 API 호출

- src/components/mypage/GroupLink.tsx
> fix : 그룹링크 가족 없는 경우 공통에러처리 엎어쓰기

- src/components/atoms/bottomSheets/commonSheet/Notice.tsx
- src/components/blocks/mypage/GroupLink.tsx
- src/components/blocks/mypage/useOpenGroupLinkSheets.ts
- src/lib/utils/crypt.ts
> fix : 그룹코드 에러처리

- src/components/atoms/buttons/Button.tsx
> fix : 애플로그인버튼 active style

- src/components/atoms/buttons/Button.tsx
- src/components/atoms/buttons/SheetButton.tsx
- src/components/atoms/progress/RefactoredProgress.stories.tsx
- src/components/atoms/progress/RefactoredProgress.tsx
- src/components/blocks/home/create/steps/Step5.tsx
- src/components/blocks/mypage/FamilyList.tsx
- src/lib/utils/messageToRNWebView.ts
- refactoredProgress 어쩌구 따로 글 작성 이유로 남겨놨는데 추후에 원래 컴포넌트 없애고 교체할 예정입니다
-
> FIX / aos에서 클립보드 안되는 오류 

- src/components/pages/OnBoarding/LoginPage.tsx
* 일부 유저 APPLE로 로그인 불가 크로스 브라우징 문제를 의심하고 기존 button 태그를 a 태그로 변경합니다.
* 관련 문제를 검색하였으나 해결방법을 찾지 못하여 다른 방법으로 구현하여 배포 후 테스트 하겠습니다.
fix/cross-browsing
> fix: 일부 유저 APPLE로 로그인 불가

- README.md
- src/components/pages/OnBoarding/LoginPage.tsx
> APPLE로 로그인 불가 테스트
